#!/bin/bash

SCREENS=$(xrandr | grep ' connected' | awk '{print $1}')
LVDS=$(xrandr | grep ' connected' | grep LVDS | awk '{print $1}')
ARGS=""
PRIMARY=""

for screen in ${SCREENS}; do
  ARGS="${ARGS} --output $screen --auto"
  if [ "${screen}" != "${LVDS}" ] ; then
    ARGS="${ARGS} --left-of ${LVDS}"
    if [ "${PRIMARY}" == "" ]; then
      ARGS="${ARGS} --primary"
      PRIMARY="${screen}"
    fi
  fi
done

xrandr ${ARGS}

